### ISSUE TITLE
Create a Postgres Docker Container

### ISSUE THREAD

**Issue by code-farmhouse** [hackoregon/transportation-systems-data-science#1]
Reference parent Issue [18](https://github.com/hackoregon/transportation-systems/issues/18)

Our data scientists need to be able to view our data within a postgres container
this env should be able to:
- [ ] host our data

- [ ] open a port to our data for localhost

- [ ] allow jupyter notebooks/anaconda to be able to access the data.

- [ ] have easy setup and install instructions

**Comment by znmeb** [comment]
This (and more) is available in <https://github.com/hackoregon/data-science-pet-containers>. The only thing missing is to "install" our two small datasets as databases. I have a way to do that with Docker; I'll have the media up on Google Drive by tomorrow. Long term we want to pull from AWS S3 automagically and securely.

**Comment by znmeb** [comment]
I'm going to close this - I'm on release v1.1.0 of the Docker images now.
